### ISSUE TITLE
Failed to load Application Version

### ISSUE THREAD

**Issue by matt-paul** [microsoft/opentelemetry-azure-monitor-js#44]
Hello.  Thanks for your work on this.  I am getting an error 'Failed to load Application version' after tracing is initialised.  From a quick dig into this, it seems like the `_appPrefix` needs one further '../' to find the package.json file that it is looking for.

Happy to submit a PR if it is helpful and assuming correct diagnosis!

https://github.com/microsoft/opentelemetry-azure-monitor-js/blob/6c10145e8db5d532f1582d8476d0802d7246c713/packages/azure-opentelemetry-exporter/src/platform/nodejs/context/context.ts#L29

https://github.com/microsoft/opentelemetry-azure-monitor-js/blob/6c10145e8db5d532f1582d8476d0802d7246c713/packages/azure-opentelemetry-exporter/src/platform/nodejs/context/context.ts#L43

**Comment by markwolff** [comment]
Hi @matt-paul yes the extra '../' seems to be necessary here. I think the change here should be trying to read two different paths, one for `ts-node` and the other for `node`. It is currently set up to read pathing for `ts-node` (and `ts-mocha`), which is not ideal for actual production environments!

I'm not quite sure how to test this though. Ideally there is a way to modify `__dirname` when running in `ts-node`.

**Comment by matt-paul** [comment]
Hello again.  Thanks for looking at this issue so quickly, I really appreciate it.  Unfortunately 'preview3' results in a similar error.  Logging the two paths (packageJsonPath and packageJsonPathTsNode) now shows the following:

<img width="1493" alt="Screenshot 2020-06-29 at 11 38 46" src="https://user-images.githubusercontent.com/13286587/86001529-e901c980-ba06-11ea-8d04-35a6a6e41d83.png">

**Comment by markwolff** [comment]
oh looks like I forgot to account for the scoped `@azure/` folder name :/
