### ISSUE TITLE
Failed to fetch persisted file

### ISSUE THREAD

**Issue by matt-paul** [microsoft/opentelemetry-azure-monitor-js#45]
It appears that 'failing to fetch persisted file' is an expected and normal outcome, and so therefore should not be an error like this?

I checked the folder there and it does not exist. However, all envelopes seem to end up successfully in Application Insights.

<img width="789" alt="Screenshot 2020-06-26 at 15 53 58" src="https://user-images.githubusercontent.com/13286587/85870775-6d650a00-b7c5-11ea-9735-b3f67e711832.png">

**Comment by markwolff** [comment]
I think you are right here that it shouldn't logged as an error. Are you seeing this logged every 60 seconds (this is the persister retry interval)? I'm thinking nothing should be logged at all for `ENOENT` errors.

However, the folder suffixed with `-undefined` name seems to be a bug that I'll address separately.

**Comment by matt-paul** [comment]
👍
